### PR TITLE
[DELIVERABLE 4] VNV Plan: Design Verification Plan

### PR DESCRIPTION
**Pull request by Ayushi1972**
## Description
Added design verification plan and checklist

## How Has This Been Tested?
Compiled locally

### CODE REVIEW

**Comment by tbrar06** [comment]
You are missing import of "amssymb" package for the checklist bullets @Ayushi1972

**Comment by Ayushi1972** [comment]
> You are missing import of "amssymb" package for the checklist bullets @Ayushi1972

Thanks, its fixed now :)

**Review by Sevhena — APPROVED** [review]
LGTM

**Review by tbrar06 — APPROVED** [review]
lgtm

**Pull request merged**
