### PR TITLE
[DELIVERABLE 2] SRS: Update Open Issues

### PR DESCRIPTION
**Pull request by Sevhena**
## Description

- Added intro to Open Issues section

## How Has This Been Tested?

- Compiled locally

### CODE REVIEW

**Review by mmyaaaaa — APPROVED** [review]
LGTM

**Review by nivethakuruparan — COMMENTED** [review]
Are we adding back the pdf in this one?

**Comment by Sevhena** [comment]
> Are we adding back the pdf in this one?

No good catch

**Review by nivethakuruparan — APPROVED** [review]
LGTM

**Pull request merged**
