### PR TITLE
[DELIVERABLE 2] SRS Document: Compliance Requirements

### LINKED ISSUE #65: [DELIVERABLE 2] SRS Document: Compliance Requirements

### PR DESCRIPTION
**Pull request by tbrar06**
## Description
Added compliance requirements

## How Has This Been Tested?
Compiled locally

Closes #65

### CODE REVIEW

**Review by Ayushi1972 — COMMENTED** [review]
You might have to add the references for this since it sounds like something you need to research

**Comment by tbrar06** [comment]
Thanks for reviewing @Ayushi1972. References are upcoming in another commit/PR

**Review by Ayushi1972 — APPROVED** [review]
LGTM

**Review by Sevhena — APPROVED** [review]
LGTM

**Pull request merged**
