### PR TITLE
[DELIVERABLE 4] VnV Plan: System Tests for NFRs + Traceability + Appendix Survey

### PR DESCRIPTION
**Pull request by Sevhena**
## Description

- Added System Tests for Non-Functional Requirements
- Added Traceability between NFRs and tests
- Added Survey for tests in Appendix

## How Has This Been Tested?

- Compiled locally

### CODE REVIEW

**Comment by Sevhena** [comment]
Ok so the changes to functional tests can be ignored, its just formatting to be consistent between sections.

2 things that I could you some advice on, 
- the immunity requirement is currently set as not tested cause honestly not sure how we are going to do that test, and 
- also the fallback req (PR-RFT 2) I'm not sure what was meant by that

**Review by mmyaaaaa — APPROVED** [review]

**Comment by tbrar06** [comment]
> Ok so the changes to functional tests can be ignored, its just formatting to be consistent between sections.
> 
> 2 things that I could you some advice on,
> 
> * the immunity requirement is currently set as not tested cause honestly not sure how we are going to do that test, and
> * also the fallback req (PR-RFT 2) I'm not sure what was meant by that

Could you clarify which doc are you referring to? I'm unable to find these requirement refs in the main branch SRS

**Comment by Sevhena** [comment]
> > Ok so the changes to functional tests can be ignored, its just formatting to be consistent between sections.
> > 2 things that I could you some advice on,
> > 
> > * the immunity requirement is currently set as not tested cause honestly not sure how we are going to do that test, and
> > * also the fallback req (PR-RFT 2) I'm not sure what was meant by that
> 
> Could you clarify which doc are you referring to? I'm unable to find these requirement refs in the main branch SRS

Mostly just the SRS. I'm not sure what test we should conduct for the immunity requirement (security section) as well as PR-RFT (performance section).

**Comment by tbrar06** [comment]
> > > Ok so the changes to functional tests can be ignored, its just formatting to be consistent between sections.
> > > 2 things that I could you some advice on,
> > > 
> > > * the immunity requirement is currently set as not tested cause honestly not sure how we are going to do that test, and
> > > * also the fallback req (PR-RFT 2) I'm not sure what was meant by that
> > 
> > 
> > Could you clarify which doc are you referring to? I'm unable to find these requirement refs in the main branch SRS
> 
> Mostly just the SRS. I'm not sure what test we should conduct for the immunity requirement (security section) as well as PR-RFT (performance section).

For the immunity requirements we could make use of services that create faux malware attacks on the tool. If the services are paid we will have to figure out to replicate at least one such attack ourselves.

**Review by tbrar06 — APPROVED** [review]
looks good!

**Pull request merged**
