### PR TITLE
[DELIVERABLE 3] Hazard Analysis: Safety and Security Requirements (incomplete)

### PR DESCRIPTION
**Pull request by nivethakuruparan**
## Description

Added safety and security requirements based on FMEA table. Probably would need to update this + add associated hazards once the table is complete.

## How Has This Been Tested?

Compiled locally

### CODE REVIEW

**Review by Sevhena — COMMENTED** [review]
Looks good so far. Just a small point, some of your reqs are bold and some aren't, so you might want to change that for consistency.

**Comment by nivethakuruparan** [comment]
> Looks good so far. Just a small point, some of your reqs are bold and some aren't, so you might want to change that for consistency.

I did that because the bold is what we don't already have on the SRS doc? I mentioned at the top? I saw another group do this.

**Review by tbrar06 — APPROVED** [review]
LGTM

**Review by mmyaaaaa — APPROVED** [review]

**Comment by Sevhena** [comment]
> > Looks good so far. Just a small point, some of your reqs are bold and some aren't, so you might want to change that for consistency.
> 
> I did that because the bold is what we don't already have on the SRS doc? I mentioned at the top? I saw another group do this.

Oh woops, I totally missed that

**Pull request merged**
