### PR TITLE
Create pull_request_template.md to Format PRs

### PR DESCRIPTION
**Pull request by nivethakuruparan**
## Description

Adds a default PR template, so they all have a similar layout (like the one used here)

## How Has This Been Tested?

I followed this [link](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository), so it should work for future PRs once this is merged

### CODE REVIEW

**Comment by Sevhena** [comment]
This is hilarious, I was also working on this lol.

**Review by Sevhena — CHANGES_REQUESTED** [review]
Could you change your file structure to look like .github/PULL_REQUEST_TEMPLATE/pull_request_template.md? That way we can have multiple templates

**Review by Sevhena — APPROVED** [review]
LGTM

**Review by tbrar06 — APPROVED** [review]
LGTM

**Pull request merged**
