### PR TITLE
[DELIVERABLE 1] Updated License.txt

### PR DESCRIPTION
**Pull request by tbrar06**
Restricts free access of software

### CODE REVIEW

**Review by Ayushi1972 — APPROVED** [review]
Nice

**Review by Sevhena — CHANGES_REQUESTED** [review]
@tbrar06 please name the pull request with the appropriate naming convention ( [DELIVERABLE #] <Changed Doc> )

**Comment by tbrar06** [comment]
@Sevhena Thanks for reviewing, PR title has been updated

**Review by Sevhena — APPROVED** [review]
LGTM

**Pull request merged**
